const fs = require('fs');
const path = require('path');

const lessonsFile = path.join(__dirname, '..', '..', 'data', 'lessons.ts');

const L5_L12_content = `
  {
    id: 'L5',
    phase: 2,
    index: 5,
    title: 'Question Words',
    title_ar: 'أدوات الاستفهام',
    objectives: [
      'Ask questions using who (nay), what (min), and where (sido)',
      'Construct simple question sentences in Mattokki',
      'Recognise that questions maintain the SOV order',
    ],
    cultural_note:
      'In Nubian villages, greetings and inquiries about well-being are extended and poetic. Asking about family, health, and neighbors is an essential social ritual before any business is discussed.',
    cultural_note_ar:
      'في القرى النوبية، السؤال عن الحال والترحيب بيكون طويل وشاعري ومهم جداً.',
    exercises: [
      {
        id: 'L5_E1',
        lesson_id: 'L5',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0001'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0001',
        options: [
          { ar: 'أنا', en: 'I', correct: true },
          { ar: 'إنت', en: 'you', correct: false },
          { ar: 'هو', en: 'he', correct: false },
          { ar: 'مين', en: 'who', correct: false },
        ],
      },
      {
        id: 'L5_E2',
        lesson_id: 'L5',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0002'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ir sido ju?',
        prompt_old_nubian: 'ⲓⲣ ⲥⲓⲇⲟ ⳝⲟⲩ?',
        prompt_arabic_transliteration: 'إير سيدو جو؟',
        morpheme_highlights: [],
        options: [
          { ar: 'إنت رايح فين؟', en: 'Where are you going?', correct: true },
          { ar: 'أنا رايح فين؟', en: 'Where am I going?', correct: false },
          { ar: 'مين اللي جه؟', en: 'Who came?', correct: false },
          { ar: 'إنت بتعمل إيه؟', en: 'What are you doing?', correct: false },
        ],
      },
      {
        id: 'L5_E3',
        lesson_id: 'L5',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0003'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'tar nay-la?',
        prompt_old_nubian: 'ⲧⲁⲣ ⲛⲁⲓ̈-ⲗⲁ?',
        prompt_arabic_transliteration: 'تار ناي-لا؟',
        morpheme_highlights: [],
        options: [
          { ar: 'من هو؟', en: 'Who is he?', correct: true },
          { ar: 'من أنا؟', en: 'Who am I?', correct: false },
          { ar: 'من أنت؟', en: 'Who are you?', correct: false },
          { ar: 'أين هو؟', en: 'Where is he?', correct: false },
        ],
      },
      {
        id: 'L5_E4',
        lesson_id: 'L5',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0002', 'xnz_0042', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: 'Do you see water?',
        prompt_ar: 'هل ترى ماء؟',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0002', surface: 'ir' },
          { role: 'O', lexeme_id: 'xnz_0042', surface: 'essi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nal' },
        ],
      },
      {
        id: 'L5_E5',
        lesson_id: 'L5',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0010'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'id-ma?',
        prompt_old_nubian: 'ⲓⲇ-ⲙⲁ?',
        prompt_arabic_transliteration: 'إيد-ما؟',
        morpheme_highlights: [{ surface: '-ma', rule_id: 'COPULA_MA' }],
        options: [
          { ar: 'هل هو رجل؟', en: 'Is he a man?', correct: true },
          { ar: 'هل هي بنت؟', en: 'Is she a girl?', correct: false },
          { ar: 'رجل طيب', en: 'A good man', correct: false },
          { ar: 'رجل (نكرة)', en: 'a man (indefinite)', correct: false },
        ],
      },
      {
        id: 'L5_E6',
        lesson_id: 'L5',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0042'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0042',
        options: [
          { ar: 'ماء', en: 'water', correct: true },
          { ar: 'نار', en: 'fire', correct: false },
          { ar: 'شمس', en: 'sun', correct: false },
          { ar: 'سما', en: 'sky', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L6',
    phase: 2,
    index: 6,
    title: 'Direct Objects (Accusative)',
    title_ar: 'المفعول به (حالة النصب)',
    objectives: [
      'Recognise the accusative case suffix -ka / -ga',
      'Observe phonological allomorphic variations (-ti after alveolar stops)',
      'Construct sentences with explicit direct object markings',
    ],
    cultural_note:
      'The Mattokki grammatical structure is rich in suffixes. Every case role (nominative, accusative, genitive) is explicitly marked. This allows flexible phrasing, though SOV remains the classical norm.',
    cultural_note_ar:
      'القواعد النوبية غنية باللواحق. كل حالة إعرابية ليها لاحقة مخصصة.',
    exercises: [
      {
        id: 'L6_E1',
        lesson_id: 'L6',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0010'], rule_ids: ['ACC_ALLOMORPH_TI'], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0010',
        correct_suffix_rule_id: 'ACC_ALLOMORPH_TI',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_GI', 'COPULA_MA'],
        expected_surface: 'it-ti',
      },
      {
        id: 'L6_E2',
        lesson_id: 'L6',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0010', 'xnz_0051'], rule_ids: ['ACC_ALLOMORPH_TI'], primary_layer: 'morphological' },
        prompt_mattokki: 'ay it-ti jomr',
        prompt_old_nubian: 'ⲁⲩ ⲓⲧ-ⲧⲓ ⳝⲟⲙⲣ',
        prompt_arabic_transliteration: 'آي إت-تي جومر',
        morpheme_highlights: [{ surface: '-ti', rule_id: 'ACC_ALLOMORPH_TI' }],
        options: [
          { ar: 'أنا بضرب الراجل', en: 'I hit the man', correct: true },
          { ar: 'الراجل بيضربني', en: 'The man hits me', correct: false },
          { ar: 'أنا راجل', en: 'I am a man', correct: false },
          { ar: 'أنا شفت الراجل', en: 'I saw the man', correct: false },
        ],
      },
      {
        id: 'L6_E3',
        lesson_id: 'L6',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0011'], rule_ids: ['ACC_ALLOMORPH_GI'], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0011',
        correct_suffix_rule_id: 'ACC_ALLOMORPH_GI',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'COPULA_MA'],
        expected_surface: 'buru-gi',
      },
      {
        id: 'L6_E4',
        lesson_id: 'L6',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0011', 'xnz_0050'], rule_ids: ['ACC_ALLOMORPH_GI'], primary_layer: 'morphological' },
        prompt_mattokki: 'ay buru-gi nalr',
        prompt_old_nubian: 'ⲁⲩ ⲃⲩⲣⲩ-ⲅⲓ ⲛⲁⲗⲣ',
        prompt_arabic_transliteration: 'آي بورو-جي نالر',
        morpheme_highlights: [{ surface: '-gi', rule_id: 'ACC_ALLOMORPH_GI' }],
        options: [
          { ar: 'أنا بشوف البنت', en: 'I see the girl', correct: true },
          { ar: 'البنت بتشوفني', en: 'The girl sees me', correct: false },
          { ar: 'أنا بنت', en: 'I am a girl', correct: false },
          { ar: 'أنا ضربت البنت', en: 'I hit the girl', correct: false },
        ],
      },
      {
        id: 'L6_E5',
        lesson_id: 'L6',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0042', 'xnz_0050'], rule_ids: ['ACC_ALLOMORPH_GI'], primary_layer: 'morphological' },
        prompt_en: 'He sees the water.',
        prompt_ar: 'هو يرى الماء.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0003', surface: 'tar' },
          { role: 'O', lexeme_id: 'xnz_0042', surface: 'essi-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nal' },
        ],
      },
      {
        id: 'L6_E6',
        lesson_id: 'L6',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0042'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0042',
        options: [
          { ar: 'ماء', en: 'water', correct: true },
          { ar: 'نار', en: 'fire', correct: false },
          { ar: 'حجر', en: 'stone', correct: false },
          { ar: 'سما', en: 'sky', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L7',
    phase: 2,
    index: 7,
    title: 'Plurals',
    title_ar: 'الجمع',
    objectives: [
      'Identify the plural suffix -gu / -rgu',
      'Observe plural agreement in noun phrases',
      'Practice pluralising pronouns and nouns',
    ],
    cultural_note:
      'Collective identity is central to Nubian society. Expressions of cooperation, like "faza" (community support in construction and harvests), are prominent, and plurals reflect a culture built on togetherness.',
    cultural_note_ar:
      'الهوية الجماعية جزء أساسي في الثقافة النوبية. التعاون والمشاركة بيظهروا في اللغة وتصريفات الجمع.',
    exercises: [
      {
        id: 'L7_E1',
        lesson_id: 'L7',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0010'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'id-gu',
        prompt_old_nubian: 'ⲓⲇ-ⲅⲩ',
        prompt_arabic_transliteration: 'إيد-جو',
        morpheme_highlights: [],
        options: [
          { ar: 'رجال', en: 'men', correct: true },
          { ar: 'راجل', en: 'a man', correct: false },
          { ar: 'بنات', en: 'girls', correct: false },
          { ar: 'أمهات', en: 'mothers', correct: false },
        ],
      },
      {
        id: 'L7_E2',
        lesson_id: 'L7',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0011'], rule_ids: [], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0011',
        correct_suffix_rule_id: 'COPULA_MA',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'INDEF_BILABIAL_BER'],
        expected_surface: 'buru-ma',
      },
      {
        id: 'L7_E3',
        lesson_id: 'L7',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0011'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'buru-gu',
        prompt_old_nubian: 'ⲃⲩⲣⲩ-ⲅⲩ',
        prompt_arabic_transliteration: 'بورو-جو',
        morpheme_highlights: [],
        options: [
          { ar: 'بنات', en: 'girls', correct: true },
          { ar: 'بنت', en: 'a girl', correct: false },
          { ar: 'رجال', en: 'men', correct: false },
          { ar: 'آباء', en: 'fathers', correct: false },
        ],
      },
      {
        id: 'L7_E4',
        lesson_id: 'L7',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0023', 'xnz_0011', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: 'We see girls.',
        prompt_ar: 'نحن نرى بنات.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0023', surface: 'ar' },
          { role: 'O', lexeme_id: 'xnz_0011', surface: 'buru-gu-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nal' },
        ],
      },
      {
        id: 'L7_E5',
        lesson_id: 'L7',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0042'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'essi-gu',
        prompt_old_nubian: 'ⲉⲥⲥⲓ-ⲅⲩ',
        prompt_arabic_transliteration: 'إيسي-جو',
        morpheme_highlights: [],
        options: [
          { ar: 'مياه (جمع)', en: 'waters', correct: true },
          { ar: 'ماء (مفرد)', en: 'water', correct: false },
          { ar: 'نار', en: 'fire', correct: false },
          { ar: 'سماوات', en: 'skies', correct: false },
        ],
      },
      {
        id: 'L7_E6',
        lesson_id: 'L7',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0010'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0010',
        options: [
          { ar: 'راجل', en: 'man', correct: true },
          { ar: 'بنت', en: 'girl', correct: false },
          { ar: 'ولد', en: 'boy', correct: false },
          { ar: 'جد', en: 'grandfather', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L8',
    phase: 2,
    index: 8,
    title: 'Genitive Case (Possession)',
    title_ar: 'المضاف والمضاف إليه (الملكية)',
    objectives: [
      'Learn the genitive suffix -n / -ni',
      'Express ownership: "X of Y"',
      'Recognise that the possessor precedes the possessed noun',
    ],
    cultural_note:
      'Possession in Mattokki is deeply relational. Saying "my brother" or "my land" uses possessive markers that differ slightly from standard nouns, showing kinship closeness.',
    cultural_note_ar:
      'التعبير عن الملكية في النوبية بيبدأ بـ المضاف إليه أولاً، زي تركيبات المضاف والمضاف إليه.',
    exercises: [
      {
        id: 'L8_E1',
        lesson_id: 'L8',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0011', 'xnz_0010'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'id-n buru',
        prompt_old_nubian: 'ⲓⲇ-ⲛ ⲃⲩⲣⲩ',
        prompt_arabic_transliteration: 'إيد-ن بورو',
        morpheme_highlights: [],
        options: [
          { ar: 'بنت الراجل', en: "the man's girl", correct: true },
          { ar: 'راجل وبنت', en: 'a man and a girl', correct: false },
          { ar: 'الراجل بيشوف البنت', en: 'the man sees the girl', correct: false },
          { ar: 'بنت جميلة', en: 'a beautiful girl', correct: false },
        ],
      },
      {
        id: 'L8_E2',
        lesson_id: 'L8',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0010'], rule_ids: [], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0010',
        correct_suffix_rule_id: 'COPULA_MA',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'INDEF_BILABIAL_BER'],
        expected_surface: 'id-ma',
      },
      {
        id: 'L8_E3',
        lesson_id: 'L8',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0012', 'xnz_0020'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'éen-n wer-i',
        prompt_old_nubian: 'ⲉⲉⲛ-ⲛ ⲟⲩⲉⲣ-ⲓ',
        prompt_arabic_transliteration: 'إين-ن ويري',
        morpheme_highlights: [],
        options: [
          { ar: 'ابن الأم', en: "the mother's son", correct: true },
          { ar: 'ولد وأم', en: 'a boy and a mother', correct: false },
          { ar: 'الأم والأب', en: 'mother and father', correct: false },
          { ar: 'الأم في البيت', en: 'mother is at home', correct: false },
        ],
      },
      {
        id: 'L8_E4',
        lesson_id: 'L8',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0013', 'xnz_0042'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: "father's water",
        prompt_ar: 'مية الأب',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0013', surface: 'baab-n' },
          { role: 'O', lexeme_id: 'xnz_0042', surface: 'essi' },
        ],
      },
      {
        id: 'L8_E5',
        lesson_id: 'L8',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0010', 'xnz_0044'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'id-n seer',
        prompt_old_nubian: 'ⲓⲇ-ⲛ ⲥⲉⲉⲣ',
        prompt_arabic_transliteration: 'إيد-ن سيير',
        morpheme_highlights: [],
        options: [
          { ar: 'حجر الراجل', en: "the man's stone", correct: true },
          { ar: 'راجل وحجر', en: 'a man and a stone', correct: false },
          { ar: 'الراجل مسك الحجر', en: 'the man held the stone', correct: false },
          { ar: 'حجر كبير', en: 'a big stone', correct: false },
        ],
      },
      {
        id: 'L8_E6',
        lesson_id: 'L8',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0012'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0012',
        options: [
          { ar: 'أم', en: 'mother', correct: true },
          { ar: 'أب', en: 'father', correct: false },
          { ar: 'بنت', en: 'girl', correct: false },
          { ar: 'ولد', en: 'boy', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L9',
    phase: 2,
    index: 9,
    title: 'Locations (Locative)',
    title_ar: 'الظرف وحروف الجر (حالة المكان)',
    objectives: [
      'Learn the locative case suffix -la / -l',
      'Say "in", "at", or "on" a place in Mattokki',
      'Observe directional motion versus static locations',
    ],
    cultural_note:
      'The Nile river (Aman) was not just water to the Nubians, it was the central spatial reference. Every location is described in relation to the flow: upstream, downstream, riverbank, or inland.',
    cultural_note_ar:
      'حالة المكان والاتجاهات عند النوبيين كانت مرتبطة بحركة النيل وجريان المياه.',
    exercises: [
      {
        id: 'L9_E1',
        lesson_id: 'L9',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0042'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'essi-la',
        prompt_old_nubian: 'ⲉⲥⲥⲓ-ⲗⲁ',
        prompt_arabic_transliteration: 'إيسي-لا',
        morpheme_highlights: [],
        options: [
          { ar: 'في الماء / للمياه', en: 'in the water / to the water', correct: true },
          { ar: 'ماء ونار', en: 'water and fire', correct: false },
          { ar: 'شرب الماية', en: 'drank the water', correct: false },
          { ar: 'الماية باردة', en: 'water is cold', correct: false },
        ],
      },
      {
        id: 'L9_E2',
        lesson_id: 'L9',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0043'], rule_ids: [], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0043',
        correct_suffix_rule_id: 'COPULA_MA',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'INDEF_BILABIAL_BER'],
        expected_surface: 'ig-ma',
      },
      {
        id: 'L9_E3',
        lesson_id: 'L9',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0043'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ig-la',
        prompt_old_nubian: 'ⲓⲅ-ⲗⲁ',
        prompt_arabic_transliteration: 'إيج-لا',
        morpheme_highlights: [],
        options: [
          { ar: 'في النار', en: 'into the fire', correct: true },
          { ar: 'نار ونور', en: 'fire and light', correct: false },
          { ar: 'تحت النار', en: 'under the fire', correct: false },
          { ar: 'الموقد', en: 'fireplace', correct: false },
        ],
      },
      {
        id: 'L9_E4',
        lesson_id: 'L9',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0046', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: 'He sees the sky.',
        prompt_ar: 'هو يرى السماء.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0003', surface: 'tar' },
          { role: 'O', lexeme_id: 'xnz_0046', surface: 'aman-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nal' },
        ],
      },
      {
        id: 'L9_E5',
        lesson_id: 'L9',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0046'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'aman-la',
        prompt_old_nubian: 'ⲁⲙⲁⲛ-ⲗⲁ',
        prompt_arabic_transliteration: 'أمان-لا',
        morpheme_highlights: [],
        options: [
          { ar: 'في السماء / للمياه', en: 'in the sky / in the water', correct: true },
          { ar: 'سماء صافية', en: 'clear sky', correct: false },
          { ar: 'مطر كثير', en: 'heavy rain', correct: false },
          { ar: 'تحت الأرض', en: 'underground', correct: false },
        ],
      },
      {
        id: 'L9_E6',
        lesson_id: 'L9',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0044'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0044',
        options: [
          { ar: 'حجر', en: 'stone', correct: true },
          { ar: 'شمس', en: 'sun', correct: false },
          { ar: 'نار', en: 'fire', correct: false },
          { ar: 'سما', en: 'sky', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L10',
    phase: 3,
    index: 10,
    title: 'Present and Past Tense',
    title_ar: 'الزمن المضارع والماضي',
    objectives: [
      'Learn present tense verb endings (-i / -ri)',
      'Learn past tense verb endings (-os / -on)',
      'Identify action flow in simple sentences',
    ],
    cultural_note:
      'Verbs in Mattokki carry aspect as well as tense. The distinction between completed actions (perfective) and ongoing actions (imperfective) shapes how narratives and stories are told.',
    cultural_note_ar:
      'تصريف الأفعال بيعبر عن الماضي والمضارع واستمرارية الحدث.',
    exercises: [
      {
        id: 'L10_E1',
        lesson_id: 'L10',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0001', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ay nalri',
        prompt_old_nubian: 'ⲁⲩ ⲛⲁⲗⲣⲓ',
        prompt_arabic_transliteration: 'آي نالري',
        morpheme_highlights: [],
        options: [
          { ar: 'أنا بشوف', en: 'I see', correct: true },
          { ar: 'أنا شفت', en: 'I saw', correct: false },
          { ar: 'أنا هشوف', en: 'I will see', correct: false },
          { ar: 'هو بيشوف', en: 'He sees', correct: false },
        ],
      },
      {
        id: 'L10_E2',
        lesson_id: 'L10',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0001'], rule_ids: [], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0001',
        correct_suffix_rule_id: 'COPULA_MA',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'INDEF_BILABIAL_BER'],
        expected_surface: 'ay-ma',
      },
      {
        id: 'L10_E3',
        lesson_id: 'L10',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0001', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ay nalos',
        prompt_old_nubian: 'ⲁⲩ ⲛⲁⲗⲟⲥ',
        prompt_arabic_transliteration: 'آي نالوس',
        morpheme_highlights: [],
        options: [
          { ar: 'أنا شفت', en: 'I saw', correct: true },
          { ar: 'أنا بشوف', en: 'I see', correct: false },
          { ar: 'هو شاف', en: 'He saw', correct: false },
          { ar: 'أنا هشوف', en: 'I will see', correct: false },
        ],
      },
      {
        id: 'L10_E4',
        lesson_id: 'L10',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0011', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: 'He saw the girl.',
        prompt_ar: 'هو شاف البنت.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0003', surface: 'tar' },
          { role: 'O', lexeme_id: 'xnz_0011', surface: 'buru-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nalon' },
        ],
      },
      {
        id: 'L10_E5',
        lesson_id: 'L10',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0002', 'xnz_0051'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ir jomri',
        prompt_old_nubian: 'ⲓⲣ ⳝⲟⲙⲣⲓ',
        prompt_arabic_transliteration: 'إير جومري',
        morpheme_highlights: [],
        options: [
          { ar: 'إنت بتضرب', en: 'You hit (present)', correct: true },
          { ar: 'أنا بضرب', en: 'I hit', correct: false },
          { ar: 'إنت ضربت', en: 'You hit (past)', correct: false },
          { ar: 'هو يضرب', en: 'He hits', correct: false },
        ],
      },
      {
        id: 'L10_E6',
        lesson_id: 'L10',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0050',
        options: [
          { ar: 'يشوف / يرى', en: 'to see', correct: true },
          { ar: 'يضرب', en: 'to hit', correct: false },
          { ar: 'يمشي', en: 'to walk', correct: false },
          { ar: 'يفتح', en: 'to open', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L11',
    phase: 3,
    index: 11,
    title: 'Future Tense',
    title_ar: 'الزمن المستقبل',
    objectives: [
      'Learn the future circumfix bi-...-r / -fa',
      'Construct simple sentences about future actions',
      'Distinguish future markers from past/present markers',
    ],
    cultural_note:
      'Hope and anticipation of the future run deep in Nubian poetry. The transition seasons of the Nile flood and harvests are always spoken of using future markers that signify hope and prayer.',
    cultural_note_ar:
      'الأمل والمستقبل جزء من الشعر النوبي وارتباطهم بمواسم فيضان النيل والزراعة.',
    exercises: [
      {
        id: 'L11_E1',
        lesson_id: 'L11',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0001', 'xnz_0050'], rule_ids: ['FUTURE_CIRCUMFIX_BI'], primary_layer: 'morphological' },
        prompt_mattokki: 'ay bi-nal-r',
        prompt_old_nubian: 'ⲁⲩ ⲃⲓ-ⲛⲁⲗ-ⲣ',
        prompt_arabic_transliteration: 'آي بي-نال-ر',
        morpheme_highlights: [{ surface: 'bi-…-r', rule_id: 'FUTURE_CIRCUMFIX_BI' }],
        options: [
          { ar: 'أنا هشوف', en: 'I will see', correct: true },
          { ar: 'أنا بشوف', en: 'I see', correct: false },
          { ar: 'أنا شفت', en: 'I saw', correct: false },
          { ar: 'هو هيشوف', en: 'He will see', correct: false },
        ],
      },
      {
        id: 'L11_E2',
        lesson_id: 'L11',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0051'], rule_ids: ['FUTURE_CIRCUMFIX_BI'], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0051',
        correct_suffix_rule_id: 'FUTURE_CIRCUMFIX_BI',
        distractor_suffix_rule_ids: ['COPULA_MA', 'INDEF_BILABIAL_BER'],
        expected_surface: 'bi-jom-r',
      },
      {
        id: 'L11_E3',
        lesson_id: 'L11',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0051'], rule_ids: ['FUTURE_CIRCUMFIX_BI'], primary_layer: 'morphological' },
        prompt_mattokki: 'tar bi-jom-r',
        prompt_old_nubian: 'ⲧⲁⲣ ⲃⲓ-ⳝⲟⲙ-ⲣ',
        prompt_arabic_transliteration: 'تار بي-جوم-ر',
        morpheme_highlights: [{ surface: 'bi-…-r', rule_id: 'FUTURE_CIRCUMFIX_BI' }],
        options: [
          { ar: 'هو هيضرب', en: 'He will hit', correct: true },
          { ar: 'هو بيضرب', en: 'He hits', correct: false },
          { ar: 'هو ضرب', en: 'He hit', correct: false },
          { ar: 'أنا هضرب', en: 'I will hit', correct: false },
        ],
      },
      {
        id: 'L11_E4',
        lesson_id: 'L11',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0023', 'xnz_0011', 'xnz_0050'], rule_ids: ['FUTURE_CIRCUMFIX_BI'], primary_layer: 'morphological' },
        prompt_en: 'We will see the girl.',
        prompt_ar: 'احنا هنشوف البنت.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0023', surface: 'ar' },
          { role: 'O', lexeme_id: 'xnz_0011', surface: 'buru-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'bi-nal-r' },
        ],
      },
      {
        id: 'L11_E5',
        lesson_id: 'L11',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0002', 'xnz_0050'], rule_ids: ['FUTURE_CIRCUMFIX_BI'], primary_layer: 'morphological' },
        prompt_mattokki: 'ir bi-nal-r',
        prompt_old_nubian: 'ⲓⲣ ⲃⲓ-ⲛⲁⲗ-ⲣ',
        prompt_arabic_transliteration: 'إير بي-نال-ر',
        morpheme_highlights: [{ surface: 'bi-…-r', rule_id: 'FUTURE_CIRCUMFIX_BI' }],
        options: [
          { ar: 'إنت هتشوف', en: 'You will see', correct: true },
          { ar: 'أنا هشوف', en: 'I will see', correct: false },
          { ar: 'إنت بتشوف', en: 'You see', correct: false },
          { ar: 'إنت شفت', en: 'You saw', correct: false },
        ],
      },
      {
        id: 'L11_E6',
        lesson_id: 'L11',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0051'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0051',
        options: [
          { ar: 'يضرب', en: 'to hit', correct: true },
          { ar: 'يشوف / يرى', en: 'to see', correct: false },
          { ar: 'يمشي', en: 'to walk', correct: false },
          { ar: 'يفتح', en: 'to open', correct: false },
        ],
      },
    ],
  },
  {
    id: 'L12',
    phase: 3,
    index: 12,
    title: 'Negation',
    title_ar: 'النفي',
    objectives: [
      'Learn the negative suffixes -mun and -kommun',
      'Negate verbs in present and past tenses',
      'Construct complete negative sentences',
    ],
    cultural_note:
      'Politeness in negation is standard. Mattokki has nuanced negative particles that soft-pedal refusal or disagreement, maintaining communal harmony in conversations.',
    cultural_note_ar:
      'النفي في النوبية المطوكية بيستخدم لواحق مهذبة ومتنوعة للمحافظة على الود والوفاق الاجتماعي.',
    exercises: [
      {
        id: 'L12_E1',
        lesson_id: 'L12',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0001', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ay nal-mun',
        prompt_old_nubian: 'ⲁⲩ ⲛⲁⲗ-ⲙⲟⲩⲛ',
        prompt_arabic_transliteration: 'آي نال-مون',
        morpheme_highlights: [],
        options: [
          { ar: 'أنا مش شايف', en: 'I do not see', correct: true },
          { ar: 'أنا شايف', en: 'I see', correct: false },
          { ar: 'أنا مش هشوف', en: 'I will not see', correct: false },
          { ar: 'أنا مش ضارب', en: 'I do not hit', correct: false },
        ],
      },
      {
        id: 'L12_E2',
        lesson_id: 'L12',
        kind: 'suffix_snap',
        morpheme_map: { lexeme_ids: ['xnz_0002'], rule_ids: [], primary_layer: 'morphological' },
        root_lexeme_id: 'xnz_0002',
        correct_suffix_rule_id: 'COPULA_MA',
        distractor_suffix_rule_ids: ['ACC_ALLOMORPH_TI', 'INDEF_BILABIAL_BER'],
        expected_surface: 'ir-ma',
      },
      {
        id: 'L12_E3',
        lesson_id: 'L12',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0001', 'xnz_0051'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'ay jom-mun',
        prompt_old_nubian: 'ⲁⲩ ⳝⲟⲙ-ⲙⲟⲩⲛ',
        prompt_arabic_transliteration: 'آي جوم-مون',
        morpheme_highlights: [],
        options: [
          { ar: 'أنا مش بضرب', en: 'I do not hit', correct: true },
          { ar: 'أنا بضرب', en: 'I hit', correct: false },
          { ar: 'أنا مش شايف', en: 'I do not see', correct: false },
          { ar: 'هو مش بضرب', en: 'He does not hit', correct: false },
        ],
      },
      {
        id: 'L12_E4',
        lesson_id: 'L12',
        kind: 'word_arrange',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0011', 'xnz_0050'], rule_ids: [], primary_layer: 'lexical' },
        prompt_en: 'He does not see the girl.',
        prompt_ar: 'هو مش شايف البنت.',
        solution: [
          { role: 'S', lexeme_id: 'xnz_0003', surface: 'tar' },
          { role: 'O', lexeme_id: 'xnz_0011', surface: 'buru-gi' },
          { role: 'V', lexeme_id: 'xnz_0050', surface: 'nal-mun' },
        ],
      },
      {
        id: 'L12_E5',
        lesson_id: 'L12',
        kind: 'mcq',
        morpheme_map: { lexeme_ids: ['xnz_0003', 'xnz_0051'], rule_ids: [], primary_layer: 'lexical' },
        prompt_mattokki: 'tar jom-kommun',
        prompt_old_nubian: 'ⲧⲁⲣ ⳝⲟⲙ-ⲕⲟⲙⲙⲟⲩⲛ',
        prompt_arabic_transliteration: 'تار جوم-كومون',
        morpheme_highlights: [],
        options: [
          { ar: 'هو لم يضرب (ماضي)', en: 'He did not hit', correct: true },
          { ar: 'هو مش بيضرب (مضارع)', en: 'He does not hit', correct: false },
          { ar: 'أنا لم أضرب', en: 'I did not hit', correct: false },
          { ar: 'هو هيضرب', en: 'He will hit', correct: false },
        ],
      },
      {
        id: 'L12_E6',
        lesson_id: 'L12',
        kind: 'audio_match',
        morpheme_map: { lexeme_ids: ['xnz_0003'], rule_ids: [], primary_layer: 'lexical' },
        audio_url: PLACEHOLDER_AUDIO,
        prompt_lexeme_id: 'xnz_0003',
        options: [
          { ar: 'هو / هي', en: 'he / she', correct: true },
          { ar: 'أنا', en: 'I', correct: false },
          { ar: 'إنت', en: 'you', correct: false },
          { ar: 'إحنا', en: 'we', correct: false },
        ],
      },
    ],
  },
`;

const fileContent = fs.readFileSync(lessonsFile, 'utf8');

// Find '// Post-process to inject real audio'
const indexWord = '// Post-process to inject real audio';
const wordIdx = fileContent.indexOf(indexWord);

if (wordIdx === -1) {
  console.error("Could not find post-processing comment!");
  process.exit(1);
}

const beforePart = fileContent.substring(0, wordIdx);
const afterPart = fileContent.substring(wordIdx);

// Find the last closing bracket '];' in beforePart
const bracketIdx = beforePart.lastIndexOf('];');
if (bracketIdx === -1) {
  console.error("Could not find ending bracket of rawLessons!");
  process.exit(1);
}

const p1 = beforePart.substring(0, bracketIdx);
const p2 = beforePart.substring(bracketIdx);

const newContent = p1 + ',' + L5_L12_content + p2 + afterPart;

fs.writeFileSync(lessonsFile, newContent, 'utf8');
console.log("Successfully generated lessons L5-L12 and wrote to lessons.ts!");
